<a href='#Array'>Array Basic</a><br>
<a href='#Arange'>Arrange</a><br>
<a href='#Split'>Split</a><br>
<a href='#Matrix'>Matrix</a><br>

<a id="Array"></a>

### Array

Ndarray(N-dimensional array) is the basic data object in Numpy, which takes in single/multiple lists or tuples.

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
# take multiple arrays
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# take array and tuple at the same time
my_mat2 = [[1,2,3],(4,5,6)]
np.array(my_mat2)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a = np.array(my_mat)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# get axes
a.ndim

2

In [17]:
# get the array length
a.size

9

In [18]:
# get the shape
a.shape

(3, 3)

In [11]:
a[1][1]

5

In [12]:
a[1,1]

5

<a id="Arange"></a>

### Arange

It generates NumPy arrays with numerical sequences that respond to particular rules.

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

<a id="Split"></a>

### Split the space in to N sub-spaces

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### random number between 0 and 1

In [15]:
np.random.rand(5)

array([0.02683876, 0.82783779, 0.09604353, 0.46838778, 0.37865984])

In [17]:
np.random.rand(2,2)

array([[0.0595452 , 0.29514311],
       [0.40879802, 0.36594932]])

### random integer, max, min and re-shape

In [22]:
np.random.randint(1,100)

15

In [3]:
np.random.randint(1,10,10)
# randint(start,end,rep times)

array([2, 9, 1, 8, 2, 6, 3, 3, 8, 6])

In [24]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Reshape changes 1d array to 2d array

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Ravel changes 2d array to 1d array

In [27]:
arr55 = arr.reshape(5,5)
arr55.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)
ranarr

array([49, 44, 28, 36, 42,  8,  5, 26, 12,  3])

In [32]:
ranarr.max()

49

In [33]:
ranarr.min()

3

find the index of max/min value

In [36]:
ranarr.argmax()

0

In [37]:
ranarr.argmin()

9

In [38]:
arr.dtype

dtype('int64')

<a id="Matrix"></a>

### Matrix Product

In [19]:
# use np.dot() to get the product of two matrixs
A = np.arange(0, 9).reshape(3, 3)
B = np.ones((3, 3))
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

### Universial functions

In [21]:
# e.g. sqrt
a = np.arange(1, 5)
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

### Aggregate functions

In [23]:
# e.g. sum
a = np.arange(1, 5)
np.sum(a)

10