<a href="#Basic">1. Basic</a><br>
<a href="#Manipulation">2. Manipulation</a><br>
<a href="#Joining">2.1 Joining</a><br>
<a href="#Splitting">2.2 Splitting</a><br>
<a href="#GeneralFunctions">3. General Functions</a><br>
<a href="#Copy">3.1 Copy</a><br>
<a href="#Vectorization">3.2 Vectorization</a><br>
<a href="#Broadcasting">3.3 Broadcasting</a><br>
<a href="#Read Data">4. Read Data From A File</a><br>

In [1]:
import numpy as np

<a id="Basic"></a>

### Basic operation

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

<a id="Manipulation"></a>

### Array Manipulation

<a id="Joining"></a>

#### 1. Joining arrays

In [7]:
A = np.ones((3, 3))
B = np.zeros((3, 3))

In [8]:
# vstack joins two 2d arrays vertically
np.vstack((A, B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# hstack joins two 2d arrays horizontally
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

These methods combine 2d arrays. There are some methods which combine 1d arrays.

In [10]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [11]:
# in column
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [12]:
# in row
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<a id="Splitting"></a>

#### 2. Splitting arrays

In [13]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
# split horizontally
[B,C] = np.hsplit(A, 2)

In [15]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [16]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [17]:
# split vertically
B,C = np.vsplit(A,2)

In [18]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
# Specify the indexes where need to be splitted
# "axis=1" indicates in column, "axis=0" indicates in row
# [1,3] means split at indexes 1 and 3
[A1,A2,A3] = np.split(A,[1,3],axis=1)

In [21]:
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [22]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [23]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [24]:
[A1,A2,A3] = np.split(A,[1,3],axis=0)

In [25]:
A1

array([[0, 1, 2, 3]])

In [26]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
A3

array([[12, 13, 14, 15]])

<a id="GeneralFunctions"></a>

### General functions

<a id="Copy"></a>

#### 1. Copy

In [28]:
# usually when assign or slice the array, the new variable points to the same object
a = np.array([1, 2, 3, 4])
c = a.copy()
c

array([1, 2, 3, 4])

In [29]:
a[0] = 99
c

array([1, 2, 3, 4])

<a id="Vectorization"></a>

#### 2. Vectorization

Vectorization is the absence of an explicit loop during the developing of the code. These loops actually cannot be omitted, but are implemented internally and then are replaced by other constructs in the code. <br>
**No need to explictly use the for loop**

<a id="Broadcasting"></a>

#### 3. Broadcasting

Broadcasting allows an operator or a function to act on two or more arrays to operate even if these arrays do not have the same shape.

In [30]:
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
b

array([0, 1, 2, 3])

In [32]:
A + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

<a id="Read Data"></a>

### Read data from file

In [33]:
# np.genfromtxt('file_name.csv/txt', delimiter='delimiter goes here', names=True/False, dtype=None)

https://docs.scipy.org/doc/numpy-1.13.0/user/basics.io.genfromtxt.html